#! /bin/sh -

getsources() {
	wget -T 5 "http://dl.voglea.com/dist/crux_gnulinux/amd64/vendor/crux-3.5-updated.iso" || return 1

	return 0
}

trysources() {
	for iso in "$PWD/crux.iso" "$PWD/crux-3.5.iso" "$PWD/crux-3.5-updated.iso"; do
		if test -f "$iso"; then
			ISO="$iso"
		fi
	done

	if test "$ISO" = ""; then
		return 1
	fi

	return 0
}

mountmedia() {
	if mountpoint -q "$PWD/cruxmedia"; then
		return 0
	fi

	mkdir -p "$PWD/cruxmedia" || return 1

	mount "$ISO" "$PWD/cruxmedia" 2>/dev/null || return 1

	return 0
}

umountmedia() {
	if mountpoint -q "$PWD/cruxmedia"; then
		umount "$PWD/cruxmedia" 2>/dev/null || return 1
	else
		return 1
	fi

	return 0
}

runtest() {
	trysources || getsources
	
	trysources || kitkat "TEST FAILED: wget http://ftp.morpheus.net/pub/linux/crux/latest/iso/crux-3.5.iso"

	mountmedia || kitkat "TEST FAILED: mount crux-3.5.iso $PWD/cruxmedia"

	boobstrap/bootstrap-templates/crux_gnulinux-embedded.bbuild || kitkat "TEST FAILED: boobstrap/bootstrap-templates/crux_gnulinux-embedded.bbuild"

	boobstrap/bootstrap-systems/default/crux_gnulinux.bbuild || kitkat "TEST FAILED: boobstrap/bootstrap-systems/default/crux_gnulinux.bbuild"

	umountmedia || kitkat "TEST NOTICE: umount $PWD/cruxmedia"
}

kitkat() {
	echo "$@"

	exit 1
}

main() {
	echo "TEST RUNNING"
	
	runtest || echo "TEST RUINED"
	
	echo "TEST ENDED"
}

main "$@"
