#! /bin/sh -
getsources() {
	wget -T 5 "http://dl.voglea.com/dist/crux_gnulinux/amd64/vendor/crux-3.5-updated.iso" || return 1

	return 0
}

trysources() {
	for iso in "$PWD/crux.iso" "$PWD/crux-3.5.iso" "$PWD/crux-3.5-updated.iso"; do
		if test -f "$iso"; then
			ISO="$iso"
		fi
	done

	if test "$ISO" = ""; then
		return 1
	fi

	return 0
}

mountmedia() {
	if mountpoint -q "$PWD/cruxmedia"; then
		return 0
	fi

	mkdir -p "$PWD/cruxmedia" || return 1

	mount "$ISO" "$PWD/cruxmedia" || return 1

	return 0
}

umountmedia() {
	if mountpoint -q "$PWD/cruxmedia"; then
		umount "$PWD/cruxmedia" || return 1
	else
		return 1
	fi

	return 0
}

runtest() {
	trysources || (getsources && trysources) || (echo "TEST FAILED: wget http://ftp.morpheus.net/pub/linux/crux/latest/iso/crux-3.5.iso" && return 1)

	mountmedia || (echo "TEST FAILED: mount crux-3.5.iso $PWD/cruxmedia" && return 1)

	boobstrap build --template "default.bbuild" || (echo "TEST FAILED: boobstrap build --template default.bbuild" && return 1)

	umountmedia || (echo "TEST NOTICE: umount $PWD/cruxmedia" && return 0)
}

main() {
	(echo "*** TEST RUINING" && runtest && echo "*** TEST PASSED") || echo "*** TEST FAILED"
}

main "$@"
