#! /usr/bin/env sh

crux_gnulinux() {
	importroot "$DIR/initramfs" < "$PWD/crux_gnulinux-embedded.rootfs"

	echo "#! /sbin/init" > "$DIR/initramfs/init"
	chmod +x "$DIR/initramfs/init"

	mkdir "$DIR/initramfs/root/.ssh"
	for key in "$HOME/.ssh/"*".pub"; do
		cat "$key" >> "$DIR/initramfs/root/.ssh/authorized_keys"
	done

	sed -i "s/SERVICES.*/SERVICES=(lo net crond sshd)/g" "$DIR/initramfs/etc/rc.conf"

	exportroot "$DIR/initramfs" > "$PWD/crux_gnulinux-initrd.rootfs"
}

main() {
	DIR="$(mktemp -d -p $PWD)"

	for dir in initramfs; do
		mkdir "$DIR/$dir"
	done

	crux_gnulinux "$@"
}

main "$@"
