#! /bin/sh -

crux_gnulinux() {
	for dir in bootstrap initramfs bootimage; do
		mkdir "$DIR/$dir"
	done

	mkbootstrap crux_gnulinux "$DIR/bootstrap"					\
											\
		--ports-dir "$PWD/ports"						\
											\
		"acl"			"iproute2"		"procps"		\
		"attr"			"iputils"		"rc"			\
		"bash"			"kbd"			"readline"		\
		"bzip2"			"kmod"			"shadow"		\
		"coreutils"		"less"			"start-stop-daemon"	\
		"dhcpcd"		"libcap"		"sysklogd"		\
		"e2fsprogs"		"libdevmapper"		"sysvinit"		\
		"eudev"			"libpcre"		"tar"			\
		"file"			"linux"			"util-linux"		\
		"filesystem"		"linux-pam"		"vi"			\
		"findutils"		"lzo"			"wget"			\
		"glibc"			"ncurses"		"which"			\
		"grep"			"openssh"		"xz"			\
		"gzip"			"openssl"		"zlib"			\
		"inetutils"		"pkgutils"

	ln -sf "bash" "$DIR/bootstrap/bin/sh"

	eval "$DIR/post-install"

	mkinitramfs "$DIR/initramfs"							\
											\
		--overlay "$DIR/bootstrap"						\
											\
		--output "$DIR/initramfs.img"

	xz -C "crc32" -T 0 -e -5 -v "$DIR/initramfs.img"

	install -D "$DIR/bootstrap/lib/modules/"*"/vmlinuz" "$DIR/bootimage/boot/vmlinuz"
	install -D "$DIR/initramfs.img.xz" "$DIR/bootimage/boot/initrd"

	mkbootisofs "$DIR/bootimage" > "$DIR/bootimage.iso"
}

main() {
	DIR="$1"

	crux_gnulinux "$@"
}

main "$@"
