#! /bin/sh -

crux_gnulinux() {
	for dir in bootstrap initramfs bootimage; do
		mkdir "$DIR/$dir"
	done

	mkbootstrap "import" "$DIR/bootstrap" < "$PWD/default.rootplug"

	mkbootstrap "crux_gnulinux" "$DIR/bootstrap"					\
											\
		--ports-dir "$PWD/ports"						\
											\
		"libevent"		"transmission"

	mkinitramfs "$DIR/initramfs"							\
											\
		--overlay "$DIR/bootstrap"						\
											\
		--output "$DIR/initramfs.img"

	xz -C "crc32" -T 0 -e -5 -v "$DIR/initramfs.img"

	install -D "$DIR/bootstrap/lib/modules/"*"/vmlinuz" "$DIR/bootimage/boot/vmlinuz"
	install -D "$DIR/initramfs.img.xz" "$DIR/bootimage/boot/initrd"

	mkbootisofs "$DIR/bootimage" > "$DIR/bootimage.iso"
}

main() {
	DIR="$1"

	crux_gnulinux "$@"
}

main "$@"
