#! /bin/sh -

crux_gnulinux() {
	for dir in bootstrap initramfs bootimage; do
		mkdir "$WORKDIR/$dir"
	done

	mkbootstrap crux_gnulinux "$WORKDIR/bootstrap"					\
											\
		--ports-dir "$PWD/ports"						\
											\
		"acl"			"iproute2"		"procps"		\
		"attr"			"iputils"		"rc"			\
		"bash"			"kbd"			"readline"		\
		"bzip2"			"kmod"			"shadow"		\
		"coreutils"		"less"			"start-stop-daemon"	\
		"dhcpcd"		"libcap"		"sysklogd"		\
		"e2fsprogs"		"libdevmapper"		"sysvinit"		\
		"eudev"			"libpcre"		"tar"			\
		"file"			"linux"			"util-linux"		\
		"filesystem"		"linux-pam"		"vi"			\
		"findutils"		"lzo"			"wget"			\
		"glibc"			"ncurses"		"which"			\
		"grep"			"openssh"		"xz"			\
		"gzip"			"openssl"		"zlib"			\
		"inetutils"		"pkgutils"


	ln -sf "bash" "$WORKDIR/bootstrap/bin/sh"

	mkinitramfs "$WORKDIR/initramfs"						\
											\
		--overlay "$WORKDIR/bootstrap"						\
											\
		--output "$WORKDIR/initramfs.img"

	# xz -C "crc32" -T 0 -9 -e -v "$WORKDIR/initramfs.img"
	# xz -C "crc32" -T 0 -e -v "$WORKDIR/initramfs.img"
	# zstd -T0 --ultra -100500 -v "$WORKDIR/initramfs.img"

	install -D "$WORKDIR/bootstrap/lib/modules/"*"/vmlinuz" "$WORKDIR/bootimage/boot/vmlinuz"
	install -D "$WORKDIR/initramfs.img" "$WORKDIR/bootimage/boot/initrd"

	mkbootisofs "$WORKDIR/bootimage" > "$WORKDIR/bootimage.iso"
}

main() {
	WORKDIR="$1"

	crux_gnulinux "$@"
}

main "$@"
