#! /bin/sh -

crux_gnulinux() {
	for dir in cruxmedia bootstrap initramfs bootimage; do
		mkdir "$WORKDIR/$dir"
	done

	for dir in configure bootimage/boot bootimage/crux; do
		mkdir "$WORKDIR/$dir"
	done

	mount "$BOOTIMG" "$WORKDIR/cruxmedia"

	mkbootstrap crux_gnulinux "$WORKDIR/bootstrap"					\
											\
		--ports-dir "$WORKDIR/cruxmedia/crux/core"				\
		--ports-dir "$WORKDIR/cruxmedia/crux/opt"				\
		--ports-dir "/usr/ports"						\
											\
		"acl"			"inetutils"		"procps"		\
		"attr"			"iproute2"		"rc"			\
		"bash"			"iputils"		"readline"		\
		"bzip2"			"kbd"			"shadow"		\
		"coreutils"		"kmod"			"start-stop-daemon"	\
		"dhcpcd"		"less"			"sysfsutils"		\
		"e2fsprogs"		"libcap"		"sysklogd"		\
		"elfutils"		"libdevmapper"		"sysvinit"		\
		"eudev"			"libpcre"		"tar"			\
		"file"			"linux"			"util-linux"		\
		"filesystem"		"linux-pam"		"vi"			\
		"findutils"		"lzo"			"wget"			\
		"gawk"			"ncurses"		"which"			\
		"glibc"			"openssh"		"xz"			\
		"grep"			"openssl"		"zlib"			\
		"gzip"			"pkgutils"

	ln -sf "bash" "$WORKDIR/bootstrap/bin/sh"

	mkinitramfs "$WORKDIR/initramfs"						\
											\
		--overlay "$WORKDIR/bootstrap"						\
		--overlay "$WORKDIR/configure"						\
		--output "$WORKDIR/initramfs.img"

	cp "/lib/modules/"*"/vmlinuz" "$WORKDIR/bootimage/boot/vmlinuz"
	mv "$WORKDIR/initramfs.img" "$WORKDIR/bootimage/boot/initrd"

	mkbootisofs "$WORKDIR/bootimage" > "$WORKDIR/bootimage.iso"

	umount "$WORKDIR/cruxmedia"
}

main() {
	BOOTIMG="$1"
	WORKDIR="$2"

	crux_gnulinux "$@"
}

main "$@"
